import {
  DOMAIN_SCHEMA_VERSION,
  type CapacityFacetId,
  type CapacityId,
  type DevelopmentBranch,
  type DevelopmentGraph,
  type DevelopmentNode,
  type GraphId,
  type NodeId,
  type PrerequisiteRef,
  type ProgrammingBoundary,
  type ProgressionTier,
} from "../contracts";
import {
  VNEXT_BASE_DEFINITION_VERSION,
  branchId,
  capacityFacetIds,
  capacityIds,
  graphIds,
  milestoneBenchmarkId,
  nodeId,
} from "./ids";

const milestone = (graphId: GraphId, id: string): PrerequisiteRef => ({
  kind: "milestone",
  milestone: { graphId, nodeId: nodeId(id) },
});

const capacityFacet = (
  capacityId: CapacityId,
  facetId: CapacityFacetId,
): PrerequisiteRef => ({ kind: "capacity-facet", capacity: { capacityId, facetId } });

type NodeOptions = Readonly<{
  id: string;
  branch: string;
  label: string;
  description: string;
  tier: ProgressionTier;
  boundary?: ProgrammingBoundary;
  status?: "available" | "missing-content";
  allOf?: readonly PrerequisiteRef[];
  anyOf?: readonly PrerequisiteRef[];
}>;

const makeNode = (graph: string, options: NodeOptions): DevelopmentNode => ({
  id: nodeId(options.id),
  branchId: branchId(options.branch),
  label: options.label,
  description: options.description,
  progressionTier: options.tier,
  programmingBoundary: options.boundary ?? "automatic",
  implementationStatus: options.status ?? "available",
  ...((options.allOf?.length || options.anyOf?.length) ? {
    prerequisiteRule: {
      ...(options.allOf?.length ? { allOf: options.allOf } : {}),
      ...(options.anyOf?.length ? { anyOf: options.anyOf } : {}),
    },
  } : {}),
  benchmarkProtocolIds: options.status === "missing-content"
    ? []
    : [milestoneBenchmarkId(graph, options.id)],
});

const branch = (id: string, label: string, description: string): DevelopmentBranch => ({
  id: branchId(id),
  label,
  description,
});

const makeGraph = (
  id: GraphId,
  kind: DevelopmentGraph["kind"],
  label: string,
  description: string,
  branches: readonly DevelopmentBranch[],
  nodes: readonly DevelopmentNode[],
): DevelopmentGraph => ({
  schemaVersion: DOMAIN_SCHEMA_VERSION,
  id,
  definitionVersion: VNEXT_BASE_DEFINITION_VERSION,
  kind,
  label,
  description,
  branches,
  nodes,
});

const plancheNodes = [
  makeNode("planche", {
    id: "controlled-planche-lean",
    branch: "planche-foundation",
    label: "Controlled planche lean",
    description: "Sustains a pain-free straight-arm forward lean with active protraction.",
    tier: "foundation",
    allOf: [
      capacityFacet(capacityIds.straightArmSupport, capacityFacetIds.tallSupport),
      capacityFacet(capacityIds.straightArmSupport, capacityFacetIds.scapularControl),
      capacityFacet(capacityIds.straightArmSupport, capacityFacetIds.protractedForwardLoading),
      capacityFacet(capacityIds.bodyLineControl, capacityFacetIds.hollowControl),
    ],
  }),
  makeNode("planche", {
    id: "toe-light-planche-loading",
    branch: "planche-foundation",
    label: "Toe-light planche loading",
    description: "Reduces foot pressure without losing straight elbows, protraction or body line.",
    tier: "foundation",
    allOf: [milestone(graphIds.planche, "controlled-planche-lean")],
  }),
  makeNode("planche", {
    id: "foot-assisted-tuck-planche",
    branch: "planche-tuck",
    label: "Foot-assisted tuck planche",
    description: "Owns a compact tuck shape with controlled, minimal foot assistance.",
    tier: "foundation",
    allOf: [milestone(graphIds.planche, "toe-light-planche-loading")],
  }),
  makeNode("planche", {
    id: "brief-floor-tuck-planche",
    branch: "planche-tuck",
    label: "Brief floor tuck planche",
    description: "Produces a brief clean unassisted tuck float and a controlled return.",
    tier: "intermediate",
    allOf: [milestone(graphIds.planche, "foot-assisted-tuck-planche")],
  }),
  makeNode("planche", {
    id: "stable-tuck-planche",
    branch: "planche-tuck",
    label: "Stable tuck planche",
    description: "Sustains an unassisted tuck planche beyond a brief attempt.",
    tier: "intermediate",
    status: "missing-content",
    allOf: [milestone(graphIds.planche, "brief-floor-tuck-planche")],
  }),
  makeNode("planche", {
    id: "advanced-tuck-planche",
    branch: "planche-tuck",
    label: "Advanced tuck planche",
    description: "Maintains protraction and body line as the hips open beyond tuck.",
    tier: "advanced",
    status: "missing-content",
    allOf: [milestone(graphIds.planche, "stable-tuck-planche")],
  }),
  makeNode("planche", {
    id: "assisted-one-leg-planche",
    branch: "planche-one-leg",
    label: "Assisted one-leg planche",
    description: "Introduces one extended leg with explicit, reproducible assistance.",
    tier: "advanced",
    status: "missing-content",
    allOf: [milestone(graphIds.planche, "advanced-tuck-planche")],
  }),
  makeNode("planche", {
    id: "one-leg-planche",
    branch: "planche-one-leg",
    label: "One-leg planche",
    description: "Sustains an unassisted one-leg planche under a stronger gate.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [milestone(graphIds.planche, "assisted-one-leg-planche")],
  }),
  makeNode("planche", {
    id: "assisted-straddle-planche",
    branch: "planche-straddle",
    label: "Assisted straddle planche",
    description: "Uses measurable assistance for a true feet-clear straddle planche shape.",
    tier: "advanced",
    status: "missing-content",
    allOf: [milestone(graphIds.planche, "advanced-tuck-planche")],
  }),
  makeNode("planche", {
    id: "stable-straddle-planche",
    branch: "planche-straddle",
    label: "Stable straddle planche",
    description: "Sustains an unassisted straddle planche with controlled exit.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [milestone(graphIds.planche, "assisted-straddle-planche")],
  }),
  makeNode("planche", {
    id: "assisted-full-planche",
    branch: "planche-full",
    label: "Assisted full planche",
    description: "Uses explicit assistance for full-planche-specific lever exposure.",
    tier: "advanced",
    status: "missing-content",
    allOf: [milestone(graphIds.planche, "stable-straddle-planche")],
  }),
  makeNode("planche", {
    id: "full-planche",
    branch: "planche-full",
    label: "Full planche",
    description: "Sustains a clean unassisted full planche under a stronger gate.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [milestone(graphIds.planche, "assisted-full-planche")],
  }),
  makeNode("planche", {
    id: "full-planche-push-up-eccentric",
    branch: "planche-dynamic",
    label: "Full-planche push-up eccentric",
    description: "Lowers from a demonstrated full Planche by bending the elbows until the shoulders reach elbow height, then lands and resets without claiming a concentric repetition.",
    tier: "specialist",
    boundary: "specialist",
    status: "missing-content",
    allOf: [
      milestone(graphIds.planche, "full-planche"),
      milestone(graphIds.parallettePushing, "advanced-forward-loaded-push-up"),
      capacityFacet(capacityIds.horizontalBentArmPush, capacityFacetIds.horizontalRepeatableStrength),
    ],
  }),
] as const;

const lSitNodes = [
  makeNode("l-sit-v-sit", {
    id: "foot-assisted-l-sit",
    branch: "l-sit-foundation",
    label: "Foot-assisted L-sit",
    description: "Maintains tall support and a long-leg shape with explicit foot assistance.",
    tier: "foundation",
    allOf: [capacityFacet(capacityIds.straightArmSupport, capacityFacetIds.tallSupport)],
  }),
  makeNode("l-sit-v-sit", {
    id: "tuck-support",
    branch: "l-sit-foundation",
    label: "Tuck support",
    description: "Floats both feet in a compact tuck while maintaining tall support.",
    tier: "foundation",
    allOf: [capacityFacet(capacityIds.straightArmSupport, capacityFacetIds.tallSupport)],
  }),
  makeNode("l-sit-v-sit", {
    id: "controlled-leg-extensions",
    branch: "l-sit-foundation",
    label: "Controlled L-sit leg extensions",
    description: "Extends and returns each leg without losing support height.",
    tier: "foundation",
    allOf: [milestone(graphIds.lSitVSit, "tuck-support")],
  }),
  makeNode("l-sit-v-sit", {
    id: "one-leg-l-sit",
    branch: "l-sit-long-leg",
    label: "One-leg L-sit",
    description: "Sustains one straight leg with balanced support on both sides.",
    tier: "intermediate",
    allOf: [
      milestone(graphIds.lSitVSit, "controlled-leg-extensions"),
      capacityFacet(capacityIds.pikeCompression, capacityFacetIds.activeSingleLegLift),
    ],
  }),
  makeNode("l-sit-v-sit", {
    id: "full-l-sit",
    branch: "l-sit-long-leg",
    label: "Full L-sit",
    description: "Produces a clean straight-leg L-sit with controlled entry and exit.",
    tier: "intermediate",
    allOf: [
      milestone(graphIds.lSitVSit, "one-leg-l-sit"),
      capacityFacet(capacityIds.pikeCompression, capacityFacetIds.usablePikeAccess),
      capacityFacet(capacityIds.pikeCompression, capacityFacetIds.activeDoubleLegLift),
    ],
  }),
  makeNode("l-sit-v-sit", {
    id: "assisted-straddle-l-sit",
    branch: "l-sit-straddle",
    label: "Assisted straddle L-sit",
    description: "Connects tall support to an assisted feet-wide straddle shape.",
    tier: "intermediate",
    allOf: [
      milestone(graphIds.lSitVSit, "controlled-leg-extensions"),
      capacityFacet(capacityIds.straddleCompression, capacityFacetIds.usableStraddleAccess),
    ],
  }),
  makeNode("l-sit-v-sit", {
    id: "stable-straddle-l-sit",
    branch: "l-sit-straddle",
    label: "Stable straddle L-sit",
    description: "Sustains a feet-clear straddle L-sit without forcing range.",
    tier: "advanced",
    status: "missing-content",
    allOf: [
      milestone(graphIds.lSitVSit, "assisted-straddle-l-sit"),
      capacityFacet(capacityIds.straddleCompression, capacityFacetIds.activeStraddleLift),
    ],
  }),
  makeNode("l-sit-v-sit", {
    id: "high-l-sit",
    branch: "v-sit",
    label: "High L-sit",
    description: "Raises the straight legs above horizontal while preserving support.",
    tier: "advanced",
    status: "missing-content",
    allOf: [
      milestone(graphIds.lSitVSit, "full-l-sit"),
      capacityFacet(capacityIds.pikeCompression, capacityFacetIds.activeDoubleLegLift),
    ],
  }),
  makeNode("l-sit-v-sit", {
    id: "assisted-v-sit",
    branch: "v-sit",
    label: "Assisted V-sit",
    description: "Uses reproducible assistance to own a V-sit-specific leg height.",
    tier: "advanced",
    status: "missing-content",
    anyOf: [
      milestone(graphIds.lSitVSit, "high-l-sit"),
      milestone(graphIds.lSitVSit, "stable-straddle-l-sit"),
    ],
  }),
  makeNode("l-sit-v-sit", {
    id: "partial-v-sit",
    branch: "v-sit",
    label: "Partial V-sit",
    description: "Controls a feet-clear V-sit range without external assistance.",
    tier: "advanced",
    status: "missing-content",
    allOf: [milestone(graphIds.lSitVSit, "assisted-v-sit")],
  }),
  makeNode("l-sit-v-sit", {
    id: "stable-v-sit",
    branch: "v-sit",
    label: "Stable V-sit",
    description: "Sustains an unassisted V-sit under a stronger gate.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [milestone(graphIds.lSitVSit, "partial-v-sit")],
  }),
  makeNode("l-sit-v-sit", {
    id: "extended-v-sit-hold",
    branch: "v-sit-specialist",
    label: "Extended V-sit hold",
    description: "Sustains a clearly higher specialist V-sit hold; press connections and manna remain separate future decisions.",
    tier: "specialist",
    boundary: "specialist",
    status: "missing-content",
    allOf: [milestone(graphIds.lSitVSit, "stable-v-sit")],
  }),
] as const;

const handstandNodes = [
  makeNode("handstand-balance", {
    id: "grounded-side-exit",
    branch: "handstand-safety",
    label: "Grounded side-exit rehearsal",
    description: "Rehearses a deliberate side exit on both sides without inversion.",
    tier: "foundation",
  }),
  makeNode("handstand-balance", {
    id: "low-inversion-side-exit",
    branch: "handstand-safety",
    label: "Low-inversion side exit",
    description: "Performs the side-exit pattern from a controlled low inversion.",
    tier: "foundation",
    allOf: [milestone(graphIds.handstandBalance, "grounded-side-exit")],
  }),
  makeNode("handstand-balance", {
    id: "supported-inversion-tolerance",
    branch: "handstand-safety",
    label: "Supported inversion tolerance",
    description: "Maintains calm wall-supported inversion with an available exit path.",
    tier: "foundation",
    allOf: [
      milestone(graphIds.handstandBalance, "low-inversion-side-exit"),
      capacityFacet(capacityIds.overheadSupport, capacityFacetIds.activeElevation),
    ],
  }),
  makeNode("handstand-balance", {
    id: "wall-height-side-exit",
    branch: "handstand-safety",
    label: "Wall-height side exit",
    description: "Exits calmly from wall-height inversion on both sides.",
    tier: "foundation",
    allOf: [milestone(graphIds.handstandBalance, "supported-inversion-tolerance")],
  }),
  makeNode("handstand-balance", {
    id: "wall-inverted-l-alignment",
    branch: "handstand-line",
    label: "Wall inverted-L alignment",
    description: "Shows a stacked shoulder line in a wall-supported inverted L.",
    tier: "foundation",
    allOf: [
      milestone(graphIds.handstandBalance, "low-inversion-side-exit"),
      capacityFacet(capacityIds.overheadSupport, capacityFacetIds.shoulderFlexionAccess),
      capacityFacet(capacityIds.bodyLineControl, capacityFacetIds.hollowControl),
    ],
  }),
  makeNode("handstand-balance", {
    id: "floor-chest-to-wall-line",
    branch: "handstand-line",
    label: "Floor chest-to-wall line",
    description: "Maintains a controlled chest-to-wall floor-handstand line without implying parallette transfer.",
    tier: "foundation",
    allOf: [
      milestone(graphIds.handstandBalance, "wall-inverted-l-alignment"),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
    ],
  }),
  makeNode("handstand-balance", {
    id: "consistent-floor-stacked-line",
    branch: "handstand-line",
    label: "Consistent floor-stacked line",
    description: "Repeats an actively elevated, controlled floor wall-handstand line.",
    tier: "intermediate",
    allOf: [milestone(graphIds.handstandBalance, "floor-chest-to-wall-line")],
  }),
  makeNode("handstand-balance", {
    id: "standing-entry-line",
    branch: "handstand-entry",
    label: "Standing entry line rehearsal",
    description: "Rehearses a measured split-leg entry line while grounded.",
    tier: "foundation",
  }),
  makeNode("handstand-balance", {
    id: "controlled-wall-entry",
    branch: "handstand-entry",
    label: "Controlled wall entry",
    description: "Enters wall support calmly without crashing into the wall.",
    tier: "foundation",
    allOf: [
      milestone(graphIds.handstandBalance, "standing-entry-line"),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
    ],
  }),
  makeNode("handstand-balance", {
    id: "stop-short-entry",
    branch: "handstand-entry",
    label: "Stop-short entry accuracy",
    description: "Stops a measured kick before heavy wall contact.",
    tier: "intermediate",
    allOf: [milestone(graphIds.handstandBalance, "controlled-wall-entry")],
  }),
  makeNode("handstand-balance", {
    id: "controlled-floor-entry",
    branch: "handstand-entry",
    label: "Controlled freestanding floor entry",
    description: "Enters a freestanding floor handstand calmly and exits without claiming balance duration.",
    tier: "intermediate",
    allOf: [
      milestone(graphIds.handstandBalance, "stop-short-entry"),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
    ],
  }),
  makeNode("handstand-balance", {
    id: "repeatable-parallette-entry",
    branch: "handstand-entry",
    label: "Repeatable freestanding parallette entry",
    description: "Repeats accurate freestanding parallette entries and planned exits.",
    tier: "intermediate",
    allOf: [
      milestone(graphIds.handstandBalance, "stop-short-entry"),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
    ],
  }),
  makeNode("handstand-balance", {
    id: "supported-weight-shift",
    branch: "handstand-balance",
    label: "Supported weight shift",
    description: "Moves pressure between hands while wall support remains available.",
    tier: "foundation",
    allOf: [milestone(graphIds.handstandBalance, "wall-inverted-l-alignment")],
  }),
  makeNode("handstand-balance", {
    id: "wall-pull-away",
    branch: "handstand-balance",
    label: "Wall pull-away",
    description: "Leaves and returns to wall support without chasing balance.",
    tier: "intermediate",
    allOf: [
      milestone(graphIds.handstandBalance, "consistent-floor-stacked-line"),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
    ],
  }),
  makeNode("handstand-balance", {
    id: "parallette-pressure-control",
    branch: "handstand-balance",
    label: "Parallette pressure control",
    description: "Uses bar pressure deliberately to correct a supported balance shift.",
    tier: "intermediate",
    allOf: [
      milestone(graphIds.handstandBalance, "supported-weight-shift"),
      milestone(graphIds.handstandBalance, "consistent-floor-stacked-line"),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
    ],
  }),
  makeNode("handstand-balance", {
    id: "controlled-short-floor-balance",
    branch: "handstand-balance",
    label: "Controlled short floor balance",
    description: "Produces a brief floor-handstand balance with a planned exit; it does not prove parallette balance.",
    tier: "intermediate",
    allOf: [
      milestone(graphIds.handstandBalance, "wall-pull-away"),
      milestone(graphIds.handstandBalance, "controlled-floor-entry"),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
    ],
  }),
  makeNode("handstand-balance", {
    id: "controlled-short-parallette-balance",
    branch: "handstand-balance",
    label: "Controlled short parallette balance",
    description: "Produces a brief freestanding parallette balance independently of entry accuracy.",
    tier: "intermediate",
    allOf: [
      milestone(graphIds.handstandBalance, "repeatable-parallette-entry"),
      milestone(graphIds.handstandBalance, "parallette-pressure-control"),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
    ],
  }),
  makeNode("handstand-balance", {
    id: "repeatable-floor-balance",
    branch: "handstand-balance",
    label: "Repeatable freestanding floor balance",
    description: "Repeats controlled floor-handstand balances across separated sessions.",
    tier: "advanced",
    status: "missing-content",
    allOf: [
      milestone(graphIds.handstandBalance, "controlled-floor-entry"),
      milestone(graphIds.handstandBalance, "controlled-short-floor-balance"),
    ],
  }),
  makeNode("handstand-balance", {
    id: "repeatable-parallette-balance",
    branch: "handstand-balance",
    label: "Repeatable freestanding parallette balance",
    description: "Repeats controlled parallette-handstand balances across separated sessions.",
    tier: "advanced",
    status: "missing-content",
    allOf: [
      milestone(graphIds.handstandBalance, "repeatable-parallette-entry"),
      milestone(graphIds.handstandBalance, "controlled-short-parallette-balance"),
      milestone(graphIds.handstandBalance, "parallette-pressure-control"),
    ],
  }),
  makeNode("handstand-balance", {
    id: "stable-longer-parallette-balance",
    branch: "handstand-balance",
    label: "Stable longer parallette balance",
    description: "Sustains a stable unassisted two-arm parallette handstand under a stronger gate.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [milestone(graphIds.handstandBalance, "repeatable-parallette-balance")],
  }),
  makeNode("handstand-balance", {
    id: "freestanding-parallette-tuck-shape-change",
    branch: "handstand-shapes",
    label: "Freestanding parallette straight-to-tuck shape change",
    description: "Changes from a straight two-arm parallette handstand to a compact tuck and back to straight without losing exit control.",
    tier: "advanced",
    status: "missing-content",
    allOf: [milestone(graphIds.handstandBalance, "repeatable-parallette-balance")],
  }),
  makeNode("handstand-balance", {
    id: "wall-weight-transfer",
    branch: "handstand-weight-transfer",
    label: "Wall weight transfer",
    description: "Transfers meaningful load between hands with wall support.",
    tier: "intermediate",
    allOf: [
      milestone(graphIds.handstandBalance, "consistent-floor-stacked-line"),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
      capacityFacet(capacityIds.bodyLineControl, capacityFacetIds.antiRotationControl),
    ],
  }),
  makeNode("handstand-balance", {
    id: "wall-micro-taps",
    branch: "handstand-weight-transfer",
    label: "Wall micro taps",
    description: "Briefly unloads one hand without collapsing the support side.",
    tier: "intermediate",
    allOf: [milestone(graphIds.handstandBalance, "wall-weight-transfer")],
  }),
  makeNode("handstand-balance", {
    id: "freestanding-weight-transfer",
    branch: "handstand-weight-transfer",
    label: "Freestanding weight transfer",
    description: "Transfers load deliberately in a stable freestanding two-arm handstand.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [
      milestone(graphIds.handstandBalance, "wall-micro-taps"),
      milestone(graphIds.handstandBalance, "stable-longer-parallette-balance"),
    ],
  }),
  makeNode("handstand-balance", {
    id: "freestanding-parallette-one-hand-light-balance",
    branch: "handstand-weight-transfer",
    label: "Freestanding parallette one-hand-light balance",
    description: "Maintains a freestanding parallette handstand while one hand becomes visibly light but retains bar contact.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [milestone(graphIds.handstandBalance, "freestanding-weight-transfer")],
  }),
  makeNode("handstand-balance", {
    id: "assisted-one-arm-parallette-balance",
    branch: "handstand-one-arm",
    label: "Assisted one-arm parallette balance",
    description: "Uses explicit coached assistance to hold a defined one-arm parallette-handstand line.",
    tier: "specialist",
    boundary: "specialist",
    status: "missing-content",
    allOf: [milestone(graphIds.handstandBalance, "freestanding-parallette-one-hand-light-balance")],
  }),
  makeNode("handstand-balance", {
    id: "one-arm-handstand",
    branch: "handstand-one-arm",
    label: "One-arm handstand",
    description: "Optional coached one-arm handstand outcome.",
    tier: "specialist",
    boundary: "specialist",
    status: "missing-content",
    allOf: [milestone(graphIds.handstandBalance, "assisted-one-arm-parallette-balance")],
  }),
] as const;

const hspuNodes = [
  makeNode("vertical-push-hspu", {
    id: "shallow-pike-push-up",
    branch: "hspu-pike",
    label: "Shallow pike push-up",
    description: "Controls a shallow vertical-push range with a stable overhead shoulder position.",
    tier: "foundation",
    allOf: [capacityFacet(capacityIds.overheadSupport, capacityFacetIds.activeElevation)],
  }),
  makeNode("vertical-push-hspu", {
    id: "floor-pike-push-up",
    branch: "hspu-pike",
    label: "Floor pike push-up",
    description: "Performs repeatable clean pike push-ups through the available floor range.",
    tier: "foundation",
    allOf: [milestone(graphIds.verticalPushHspu, "shallow-pike-push-up")],
  }),
  makeNode("vertical-push-hspu", {
    id: "parallette-pike-push-up",
    branch: "hspu-pike",
    label: "Parallette pike push-up",
    description: "Controls pike pressing on parallettes through a clear pain-free range.",
    tier: "intermediate",
    allOf: [milestone(graphIds.verticalPushHspu, "floor-pike-push-up")],
  }),
  makeNode("vertical-push-hspu", {
    id: "controlled-pike-eccentric",
    branch: "hspu-pike",
    label: "Controlled pike eccentric",
    description: "Lowers slowly through pike-push range without implying concentric strength.",
    tier: "intermediate",
    allOf: [milestone(graphIds.verticalPushHspu, "parallette-pike-push-up")],
  }),
  makeNode("vertical-push-hspu", {
    id: "elevated-deep-pike-push-up",
    branch: "hspu-pike",
    label: "Elevated deep pike push-up",
    description: "Bridges current pike strength into deeper, more vertical pressing.",
    tier: "intermediate",
    status: "missing-content",
    allOf: [milestone(graphIds.verticalPushHspu, "controlled-pike-eccentric")],
  }),
  makeNode("vertical-push-hspu", {
    id: "wall-hspu-bottom-position-exit",
    branch: "hspu-wall",
    label: "Wall HSPU bottom-position exit",
    description: "Demonstrates a controlled bailout from the standard wall-HSPU bottom position, with the crown at a padded target level with the bar tops, before eccentric work.",
    tier: "intermediate",
    status: "missing-content",
    allOf: [
      milestone(graphIds.verticalPushHspu, "elevated-deep-pike-push-up"),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
      milestone(graphIds.handstandBalance, "consistent-floor-stacked-line"),
      capacityFacet(capacityIds.overheadSupport, capacityFacetIds.stackedSupport),
      capacityFacet(capacityIds.verticalBentArmPush, capacityFacetIds.pikeRange),
    ],
  }),
  makeNode("vertical-push-hspu", {
    id: "wall-hspu-eccentric",
    branch: "hspu-wall",
    label: "Wall HSPU eccentric",
    description: "Controls a wall-supported inverted descent to a safe bottom position.",
    tier: "intermediate",
    status: "missing-content",
    allOf: [
      milestone(graphIds.verticalPushHspu, "wall-hspu-bottom-position-exit"),
      capacityFacet(capacityIds.verticalBentArmPush, capacityFacetIds.deepPikeControl),
    ],
  }),
  makeNode("vertical-push-hspu", {
    id: "assisted-wall-hspu-concentric",
    branch: "hspu-wall",
    label: "Assisted wall HSPU concentric",
    description: "Uses explicit assistance for a controlled wall-supported concentric.",
    tier: "intermediate",
    status: "missing-content",
    allOf: [
      milestone(graphIds.verticalPushHspu, "wall-hspu-eccentric"),
      capacityFacet(capacityIds.verticalBentArmPush, capacityFacetIds.verticalRepeatableStrength),
    ],
  }),
  makeNode("vertical-push-hspu", {
    id: "partial-wall-hspu",
    branch: "hspu-wall",
    label: "Partial wall HSPU",
    description: "Owns a reproducible unassisted wall HSPU range.",
    tier: "intermediate",
    status: "missing-content",
    allOf: [milestone(graphIds.verticalPushHspu, "assisted-wall-hspu-concentric")],
  }),
  makeNode("vertical-push-hspu", {
    id: "full-wall-hspu",
    branch: "hspu-wall",
    label: "Full wall HSPU",
    description: "Performs a full wall-supported HSPU through the approved range.",
    tier: "advanced",
    status: "missing-content",
    allOf: [milestone(graphIds.verticalPushHspu, "partial-wall-hspu")],
  }),
  makeNode("vertical-push-hspu", {
    id: "deficit-wall-hspu-bottom-position-exit",
    branch: "hspu-wall",
    label: "Deficit wall HSPU bottom-position exit",
    description: "Demonstrates a controlled bailout from the exact deeper target proposed for deficit wall-HSPU work before that range is trained.",
    tier: "advanced",
    status: "missing-content",
    allOf: [
      milestone(graphIds.verticalPushHspu, "full-wall-hspu"),
      milestone(graphIds.verticalPushHspu, "wall-hspu-bottom-position-exit"),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
    ],
  }),
  makeNode("vertical-push-hspu", {
    id: "deficit-wall-hspu",
    branch: "hspu-wall",
    label: "Deficit wall HSPU",
    description: "Presses below the standard bar-top bottom landmark to an explicitly deeper reviewed target.",
    tier: "advanced",
    status: "missing-content",
    allOf: [
      milestone(graphIds.verticalPushHspu, "full-wall-hspu"),
      milestone(graphIds.verticalPushHspu, "deficit-wall-hspu-bottom-position-exit"),
    ],
  }),
  makeNode("vertical-push-hspu", {
    id: "freestanding-hspu-eccentric",
    branch: "hspu-freestanding",
    label: "Freestanding HSPU eccentric",
    description: "Controls an unassisted inverted descent with reliable balance and exit.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [
      milestone(graphIds.verticalPushHspu, "full-wall-hspu"),
      milestone(graphIds.verticalPushHspu, "wall-hspu-bottom-position-exit"),
      milestone(graphIds.handstandBalance, "stable-longer-parallette-balance"),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
    ],
  }),
  makeNode("vertical-push-hspu", {
    id: "partial-freestanding-hspu",
    branch: "hspu-freestanding",
    label: "Partial freestanding HSPU",
    description: "Performs a controlled partial concentric without losing balance.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [milestone(graphIds.verticalPushHspu, "freestanding-hspu-eccentric")],
  }),
  makeNode("vertical-push-hspu", {
    id: "full-freestanding-hspu",
    branch: "hspu-freestanding",
    label: "Full freestanding HSPU",
    description: "Performs a full freestanding HSPU under a stronger gate.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [milestone(graphIds.verticalPushHspu, "partial-freestanding-hspu")],
  }),
  makeNode("vertical-push-hspu", {
    id: "deficit-freestanding-hspu",
    branch: "hspu-freestanding",
    label: "Deficit freestanding HSPU",
    description: "Extends freestanding HSPU depth with controlled balance and exit.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [
      milestone(graphIds.verticalPushHspu, "full-freestanding-hspu"),
      milestone(graphIds.verticalPushHspu, "deficit-wall-hspu-bottom-position-exit"),
    ],
  }),
  makeNode("vertical-push-hspu", {
    id: "ninety-degree-hspu",
    branch: "hspu-specialist",
    label: "90-degree HSPU",
    description: "Optional high-load 90-degree handstand push-up development.",
    tier: "specialist",
    boundary: "specialist",
    status: "missing-content",
    allOf: [
      milestone(graphIds.verticalPushHspu, "deficit-freestanding-hspu"),
      milestone(graphIds.parallettePushing, "advanced-forward-loaded-push-up"),
    ],
  }),
] as const;

const pressNodes = [
  makeNode("press-to-handstand", {
    id: "feet-assisted-tuck-press-load",
    branch: "press-foundation",
    label: "Feet-assisted tuck press load",
    description: "Coordinates a compact tuck, forward straight-arm load and overhead shoulder intent while both feet retain explicit assistance.",
    tier: "foundation",
    status: "missing-content",
    allOf: [
      capacityFacet(capacityIds.straightArmSupport, capacityFacetIds.tallSupport),
      capacityFacet(capacityIds.straightArmSupport, capacityFacetIds.scapularControl),
      capacityFacet(capacityIds.overheadSupport, capacityFacetIds.shoulderFlexionAccess),
      capacityFacet(capacityIds.overheadSupport, capacityFacetIds.activeElevation),
      capacityFacet(capacityIds.overheadSupport, capacityFacetIds.stackedSupport),
      capacityFacet(capacityIds.bodyLineControl, capacityFacetIds.hollowControl),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
    ],
    anyOf: [
      capacityFacet(capacityIds.pikeCompression, capacityFacetIds.activeDoubleLegLift),
      capacityFacet(capacityIds.straddleCompression, capacityFacetIds.activeStraddleLift),
    ],
  }),
  makeNode("press-to-handstand", {
    id: "assisted-bent-arm-tuck-press",
    branch: "press-bent-arm",
    label: "Assisted bent-arm tuck press",
    description: "Develops the distinct bent-arm tuck-press branch with assistance.",
    tier: "intermediate",
    status: "missing-content",
    allOf: [
      milestone(graphIds.pressToHandstand, "feet-assisted-tuck-press-load"),
      capacityFacet(capacityIds.verticalBentArmPush, capacityFacetIds.pikeRange),
      capacityFacet(capacityIds.verticalBentArmPush, capacityFacetIds.deepPikeControl),
      capacityFacet(capacityIds.verticalBentArmPush, capacityFacetIds.verticalRepeatableStrength),
    ],
  }),
  makeNode("press-to-handstand", {
    id: "full-bent-arm-tuck-press",
    branch: "press-bent-arm",
    label: "Full bent-arm tuck press",
    description: "Performs an unassisted bent-arm tuck press under a stronger gate.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [milestone(graphIds.pressToHandstand, "assisted-bent-arm-tuck-press")],
  }),
  makeNode("press-to-handstand", {
    id: "assisted-straddle-press",
    branch: "press-straddle",
    label: "Assisted straight-arm straddle press",
    description: "Uses explicit assistance for straight-arm straddle press mechanics.",
    tier: "intermediate",
    status: "missing-content",
    allOf: [
      milestone(graphIds.pressToHandstand, "feet-assisted-tuck-press-load"),
      capacityFacet(capacityIds.straddleCompression, capacityFacetIds.usableStraddleAccess),
      capacityFacet(capacityIds.straddleCompression, capacityFacetIds.activeStraddleLift),
    ],
  }),
  makeNode("press-to-handstand", {
    id: "straddle-press-negative",
    branch: "press-straddle",
    label: "Straddle press negative",
    description: "Lowers from handstand through a controlled straight-arm straddle path.",
    tier: "advanced",
    status: "missing-content",
    allOf: [
      milestone(graphIds.pressToHandstand, "assisted-straddle-press"),
      milestone(graphIds.handstandBalance, "consistent-floor-stacked-line"),
    ],
  }),
  makeNode("press-to-handstand", {
    id: "full-straddle-press",
    branch: "press-straddle",
    label: "Full straight-arm straddle press",
    description: "Performs an unassisted straight-arm straddle press under a stronger gate.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [milestone(graphIds.pressToHandstand, "straddle-press-negative")],
  }),
  makeNode("press-to-handstand", {
    id: "assisted-pike-press",
    branch: "press-pike",
    label: "Assisted straight-arm pike press",
    description: "Uses explicit assistance for straight-arm pike press mechanics.",
    tier: "advanced",
    status: "missing-content",
    allOf: [
      milestone(graphIds.pressToHandstand, "feet-assisted-tuck-press-load"),
      capacityFacet(capacityIds.pikeCompression, capacityFacetIds.usablePikeAccess),
      capacityFacet(capacityIds.pikeCompression, capacityFacetIds.activeDoubleLegLift),
    ],
  }),
  makeNode("press-to-handstand", {
    id: "pike-press-negative",
    branch: "press-pike",
    label: "Pike press negative",
    description: "Lowers from handstand through a controlled straight-arm pike path.",
    tier: "advanced",
    status: "missing-content",
    allOf: [
      milestone(graphIds.pressToHandstand, "assisted-pike-press"),
      milestone(graphIds.handstandBalance, "consistent-floor-stacked-line"),
    ],
  }),
  makeNode("press-to-handstand", {
    id: "full-pike-press",
    branch: "press-pike",
    label: "Full straight-arm pike press",
    description: "Performs an unassisted straight-arm pike press under a stronger gate.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [milestone(graphIds.pressToHandstand, "pike-press-negative")],
  }),
  makeNode("press-to-handstand", {
    id: "repeated-straddle-presses",
    branch: "press-specialist",
    label: "Repeated straight-arm straddle presses",
    description: "Performs a defined set of repeated straight-arm straddle presses without merging stalder or planche combinations.",
    tier: "specialist",
    boundary: "specialist",
    status: "missing-content",
    allOf: [milestone(graphIds.pressToHandstand, "full-straddle-press")],
  }),
  makeNode("press-to-handstand", {
    id: "repeated-pike-presses",
    branch: "press-specialist",
    label: "Repeated straight-arm pike presses",
    description: "Performs a defined set of repeated straight-arm pike presses as a distinct specialist outcome.",
    tier: "specialist",
    boundary: "specialist",
    status: "missing-content",
    allOf: [milestone(graphIds.pressToHandstand, "full-pike-press")],
  }),
] as const;

const pushingNodes = [
  makeNode("parallette-pushing", {
    id: "knee-push-up",
    branch: "pushing-foundation",
    label: "Knee push-up",
    description: "Controls a knee-supported horizontal push through a clean range.",
    tier: "foundation",
  }),
  makeNode("parallette-pushing", {
    id: "floor-push-up",
    branch: "pushing-foundation",
    label: "Floor push-up",
    description: "Performs repeatable full-body floor push-ups through a clean range.",
    tier: "foundation",
    allOf: [
      milestone(graphIds.parallettePushing, "knee-push-up"),
      capacityFacet(capacityIds.bodyLineControl, capacityFacetIds.hollowControl),
    ],
  }),
  makeNode("parallette-pushing", {
    id: "controlled-parallette-push-up",
    branch: "pushing-foundation",
    label: "Controlled parallette push-up",
    description: "Controls a neutral-grip parallette push-up through the approved range.",
    tier: "foundation",
    allOf: [
      milestone(graphIds.parallettePushing, "floor-push-up"),
      capacityFacet(capacityIds.horizontalBentArmPush, capacityFacetIds.horizontalRange),
    ],
  }),
  makeNode("parallette-pushing", {
    id: "tempo-push-up",
    branch: "pushing-range",
    label: "Tempo push-up",
    description: "Maintains body line and range under a deliberate tempo.",
    tier: "intermediate",
    allOf: [milestone(graphIds.parallettePushing, "controlled-parallette-push-up")],
  }),
  makeNode("parallette-pushing", {
    id: "staggered-parallette-push-up",
    branch: "pushing-asymmetry",
    label: "Staggered parallette push-up",
    description: "Controls a modest stagger without trunk rotation or range loss.",
    tier: "intermediate",
    allOf: [
      milestone(graphIds.parallettePushing, "controlled-parallette-push-up"),
      capacityFacet(capacityIds.bodyLineControl, capacityFacetIds.antiRotationControl),
    ],
  }),
  makeNode("parallette-pushing", {
    id: "pseudo-planche-push-up",
    branch: "pushing-forward-loaded",
    label: "Pseudo-planche push-up",
    description: "Controls bent-arm pressing under increased forward load.",
    tier: "intermediate",
    allOf: [
      milestone(graphIds.parallettePushing, "controlled-parallette-push-up"),
      milestone(graphIds.planche, "controlled-planche-lean"),
    ],
  }),
  makeNode("parallette-pushing", {
    id: "deep-deficit-parallette-push-up",
    branch: "pushing-range",
    label: "Deep deficit parallette push-up",
    description: "Extends range below the hands with explicit shoulder-control criteria.",
    tier: "advanced",
    status: "missing-content",
    allOf: [
      milestone(graphIds.parallettePushing, "tempo-push-up"),
      capacityFacet(capacityIds.horizontalBentArmPush, capacityFacetIds.paralletteRangeControl),
    ],
  }),
  makeNode("parallette-pushing", {
    id: "advanced-forward-loaded-push-up",
    branch: "pushing-forward-loaded",
    label: "Advanced forward-loaded push-up",
    description: "Increases forward bent-arm load under a stronger gate.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [
      milestone(graphIds.parallettePushing, "pseudo-planche-push-up"),
      capacityFacet(capacityIds.horizontalBentArmPush, capacityFacetIds.horizontalRepeatableStrength),
    ],
  }),
  makeNode("parallette-pushing", {
    id: "full-planche-push-up",
    branch: "pushing-specialist",
    label: "Full Planche push-up",
    description: "From a locked-elbow full Planche, lowers until the shoulders reach elbow height and presses back to the same locked-elbow full-Planche line without foot contact or lever shortening.",
    tier: "specialist",
    boundary: "specialist",
    status: "missing-content",
    allOf: [
      milestone(graphIds.parallettePushing, "advanced-forward-loaded-push-up"),
      milestone(graphIds.planche, "full-planche"),
      milestone(graphIds.planche, "full-planche-push-up-eccentric"),
    ],
  }),
] as const;

const transitionNodes = [
  makeNode("transitions", {
    id: "support-to-tuck",
    branch: "transition-support-l-sit",
    label: "Support to tuck",
    description: "Moves between tall support and tuck without uncontrolled foot contact.",
    tier: "foundation",
    allOf: [milestone(graphIds.lSitVSit, "tuck-support")],
  }),
  makeNode("transitions", {
    id: "tuck-to-one-leg-l-sit",
    branch: "transition-support-l-sit",
    label: "Tuck to one-leg L-sit",
    description: "Transitions from tuck to a controlled one-leg L-sit and back.",
    tier: "intermediate",
    allOf: [
      milestone(graphIds.transitions, "support-to-tuck"),
      milestone(graphIds.lSitVSit, "one-leg-l-sit"),
    ],
  }),
  makeNode("transitions", {
    id: "tuck-to-full-l-sit",
    branch: "transition-support-l-sit",
    label: "Tuck to full L-sit",
    description: "Transitions from tuck to a full L-sit without swinging or shoulder collapse.",
    tier: "intermediate",
    allOf: [
      milestone(graphIds.transitions, "tuck-to-one-leg-l-sit"),
      milestone(graphIds.lSitVSit, "full-l-sit"),
    ],
  }),
  makeNode("transitions", {
    id: "entry-balance-safe-exit",
    branch: "transition-handstand",
    label: "Entry, balance and safe exit",
    description: "Joins an accurate entry, short balance and planned side exit.",
    tier: "intermediate",
    allOf: [
      milestone(graphIds.handstandBalance, "repeatable-parallette-entry"),
      milestone(graphIds.handstandBalance, "controlled-short-parallette-balance"),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
    ],
  }),
  makeNode("transitions", {
    id: "l-sit-to-tuck-planche",
    branch: "transition-l-sit-planche",
    label: "L-sit to tuck planche",
    description: "Links controlled L-sit and tuck-planche endpoints through a distinct transition.",
    tier: "intermediate",
    status: "missing-content",
    allOf: [
      milestone(graphIds.lSitVSit, "full-l-sit"),
      milestone(graphIds.planche, "stable-tuck-planche"),
    ],
  }),
  makeNode("transitions", {
    id: "tuck-planche-to-l-sit",
    branch: "transition-l-sit-planche",
    label: "Tuck planche to L-sit",
    description: "Controls the reverse tuck-planche-to-L-sit connection as its own transition outcome.",
    tier: "intermediate",
    status: "missing-content",
    allOf: [
      milestone(graphIds.planche, "stable-tuck-planche"),
      milestone(graphIds.lSitVSit, "full-l-sit"),
    ],
  }),
  makeNode("transitions", {
    id: "wall-handstand-to-straddle-stand-lower",
    branch: "transition-handstand-lower",
    label: "Wall handstand to straddle-stand lower",
    description: "Lowers from a wall handstand through a controlled straight-arm straddle path to both feet on the floor.",
    tier: "intermediate",
    status: "missing-content",
    allOf: [
      milestone(graphIds.handstandBalance, "consistent-floor-stacked-line"),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
      capacityFacet(capacityIds.straddleCompression, capacityFacetIds.usableStraddleAccess),
    ],
  }),
  makeNode("transitions", {
    id: "feet-assisted-straddle-press-to-wall-handstand",
    branch: "transition-press-handstand",
    label: "Feet-assisted straddle press to wall handstand",
    description: "Connects the assisted straight-arm straddle press path to a controlled wall-handstand endpoint without a reset.",
    tier: "intermediate",
    status: "missing-content",
    allOf: [
      milestone(graphIds.pressToHandstand, "assisted-straddle-press"),
      milestone(graphIds.handstandBalance, "consistent-floor-stacked-line"),
    ],
  }),
  makeNode("transitions", {
    id: "straddle-l-press-handstand",
    branch: "transition-press-handstand",
    label: "Straddle L-sit to press handstand",
    description: "Connects straddle-L support, straight-arm press and handstand under a stronger gate.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [
      milestone(graphIds.lSitVSit, "stable-straddle-l-sit"),
      milestone(graphIds.pressToHandstand, "full-straddle-press"),
      milestone(graphIds.handstandBalance, "stable-longer-parallette-balance"),
    ],
  }),
  makeNode("transitions", {
    id: "full-l-pike-press-to-handstand",
    branch: "transition-press-handstand",
    label: "Full L-sit through pike press to handstand",
    description: "Connects a full L-sit to a straight-arm pike press and stable parallette handstand without a reset.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [
      milestone(graphIds.lSitVSit, "full-l-sit"),
      milestone(graphIds.pressToHandstand, "full-pike-press"),
      milestone(graphIds.handstandBalance, "stable-longer-parallette-balance"),
    ],
  }),
  makeNode("transitions", {
    id: "handstand-to-l-sit-negative",
    branch: "transition-handstand-lower",
    label: "Handstand to L-sit negative",
    description: "Controls the full negative connection from handstand toward L-sit.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [
      milestone(graphIds.transitions, "wall-handstand-to-straddle-stand-lower"),
      milestone(graphIds.pressToHandstand, "pike-press-negative"),
      milestone(graphIds.handstandBalance, "stable-longer-parallette-balance"),
      milestone(graphIds.handstandBalance, "wall-height-side-exit"),
      milestone(graphIds.lSitVSit, "full-l-sit"),
      capacityFacet(capacityIds.bodyLineControl, capacityFacetIds.integratedLine),
    ],
  }),
  makeNode("transitions", {
    id: "straddle-planche-to-handstand-press",
    branch: "transition-planche-handstand",
    label: "Straddle planche to handstand press",
    description: "Presses from a stable straddle planche into a stable two-arm parallette handstand as one defined direction.",
    tier: "advanced",
    boundary: "stronger-gated",
    status: "missing-content",
    allOf: [
      milestone(graphIds.planche, "stable-straddle-planche"),
      milestone(graphIds.pressToHandstand, "full-straddle-press"),
      milestone(graphIds.handstandBalance, "stable-longer-parallette-balance"),
    ],
  }),
  makeNode("transitions", {
    id: "full-planche-to-handstand-transition",
    branch: "transition-specialist",
    label: "Full planche to handstand transition",
    description: "Optional specialist press from a demonstrated full planche into a stable two-arm parallette handstand.",
    tier: "specialist",
    boundary: "specialist",
    status: "missing-content",
    allOf: [
      milestone(graphIds.planche, "full-planche"),
      milestone(graphIds.pressToHandstand, "full-straddle-press"),
      milestone(graphIds.handstandBalance, "stable-longer-parallette-balance"),
      capacityFacet(capacityIds.bodyLineControl, capacityFacetIds.integratedLine),
    ],
  }),
  makeNode("transitions", {
    id: "ninety-degree-handstand-to-planche-transition",
    branch: "transition-specialist",
    label: "90-degree handstand-to-planche transition",
    description: "Optional specialist negative from handstand through the 90-degree position to a demonstrated full planche.",
    tier: "specialist",
    boundary: "specialist",
    status: "missing-content",
    allOf: [
      milestone(graphIds.verticalPushHspu, "ninety-degree-hspu"),
      milestone(graphIds.planche, "full-planche"),
      milestone(graphIds.handstandBalance, "stable-longer-parallette-balance"),
    ],
  }),
] as const;

export const developmentGraphs = [
  makeGraph(
    graphIds.planche,
    "outcome-family",
    "Planche",
    "Static straight-arm planche outcomes with distinct tuck, one-leg, straddle and full branches plus exact specialist eccentric pressing.",
    [
      branch("planche-foundation", "Foundation loading", "Straight-arm protraction and forward-load landmarks."),
      branch("planche-tuck", "Tuck", "Assisted through advanced-tuck outcomes."),
      branch("planche-one-leg", "One-leg", "One-leg-specific assisted development."),
      branch("planche-straddle", "Straddle", "True feet-clear straddle outcomes, not straddle leans."),
      branch("planche-full", "Full", "Full-planche-specific assisted and unassisted outcomes."),
      branch("planche-dynamic", "Dynamic specialist", "Optional exact Planche push-up eccentric, separate from static holds and the later concentric outcome."),
    ],
    plancheNodes,
  ),
  makeGraph(
    graphIds.lSitVSit,
    "outcome-family",
    "L-Sit / V-Sit",
    "Support and compression outcomes with separate long-leg, straddle and V-sit branches.",
    [
      branch("l-sit-foundation", "Foundation", "Assisted support, tuck and controlled extension outcomes."),
      branch("l-sit-long-leg", "Long-leg L-sit", "One-leg, full and stable L-sit outcomes."),
      branch("l-sit-straddle", "Straddle L-sit", "A parallel morphology-sensitive straddle branch."),
      branch("v-sit", "V-sit", "High-L through stable V-sit development."),
      branch("v-sit-specialist", "V-sit specialist", "Optional extended, press-connected and manna-specific work."),
    ],
    lSitNodes,
  ),
  makeGraph(
    graphIds.handstandBalance,
    "outcome-family",
    "Handstand Balance",
    "Separate safety, line, entry, pressure/balance, shape and weight-transfer branches.",
    [
      branch("handstand-safety", "Safety and inversion", "Progressive exit competence and inversion tolerance."),
      branch("handstand-line", "Line", "Supported alignment through consistent stacked support."),
      branch("handstand-entry", "Entry", "Grounded rehearsal through repeatable freestanding entry."),
      branch("handstand-balance", "Balance and pressure", "Supported pressure work through freestanding balance."),
      branch("handstand-shapes", "Shapes", "Controlled two-arm handstand shape changes."),
      branch("handstand-weight-transfer", "Weight transfer", "Wall-supported through advanced two-arm asymmetry."),
      branch("handstand-one-arm", "One-arm specialist", "Optional coached one-arm preparation."),
    ],
    handstandNodes,
  ),
  makeGraph(
    graphIds.verticalPushHspu,
    "outcome-family",
    "Vertical Push / HSPU",
    "Pike, wall-supported and freestanding vertical-push branches with eccentric and concentric evidence kept distinct.",
    [
      branch("hspu-pike", "Pike press", "Shallow through elevated/deep pike strength."),
      branch("hspu-wall", "Wall HSPU", "Wall eccentric, assisted concentric, full and deficit outcomes."),
      branch("hspu-freestanding", "Freestanding HSPU", "Stronger-gated unassisted eccentric and concentric outcomes."),
      branch("hspu-specialist", "HSPU specialist", "Optional 90-degree pressing."),
    ],
    hspuNodes,
  ),
  makeGraph(
    graphIds.pressToHandstand,
    "outcome-family",
    "Press to Handstand",
    "Distinct bent-arm tuck, straight-arm straddle and straight-arm pike press branches.",
    [
      branch("press-foundation", "Press foundation", "Assisted press-specific loading and coordination."),
      branch("press-bent-arm", "Bent-arm tuck", "A related but non-prerequisite branch for bent-arm pressing."),
      branch("press-straddle", "Straight-arm straddle", "Assisted, negative and full straddle press outcomes."),
      branch("press-pike", "Straight-arm pike", "Higher-compression assisted, negative and full pike press outcomes."),
      branch("press-specialist", "Press specialist", "Optional repeat and advanced entry combinations."),
    ],
    pressNodes,
  ),
  makeGraph(
    graphIds.parallettePushing,
    "foundation-track",
    "Parallette Pushing",
    "General horizontal pushing kept distinct from planche-specific and HSPU strength.",
    [
      branch("pushing-foundation", "Foundation", "Knee, floor and parallette push-up control."),
      branch("pushing-range", "Range and tempo", "Tempo and increased-range development."),
      branch("pushing-asymmetry", "Asymmetry", "Controlled staggered pressing."),
      branch("pushing-forward-loaded", "Forward-loaded", "Bent-arm forward-load progression."),
      branch("pushing-specialist", "Pushing specialist", "Optional planche-specific dynamic pressing."),
    ],
    pushingNodes,
  ),
  makeGraph(
    graphIds.transitions,
    "composite",
    "Transitions",
    "Cross-family transitions that require endpoint milestones plus distinct transition evidence.",
    [
      branch("transition-support-l-sit", "Support and L-sit", "Support-to-tuck and tuck-to-L-sit transitions."),
      branch("transition-handstand", "Handstand chain", "Entry, balance and safe exit integration."),
      branch("transition-l-sit-planche", "L-sit and planche", "Cross-family L-sit/planche connections."),
      branch("transition-handstand-lower", "Handstand lowers", "Controlled lowering and negative connections."),
      branch("transition-press-handstand", "Press and handstand", "Assisted through stronger-gated press connections."),
      branch("transition-planche-handstand", "Planche and handstand", "Advanced planche/handstand connections."),
      branch("transition-specialist", "Transition specialist", "Optional high-load multi-skill sequences."),
    ],
    transitionNodes,
  ),
] as const satisfies readonly DevelopmentGraph[];

export const developmentGraphById = new Map(
  developmentGraphs.map((graph) => [graph.id, graph] as const),
);

export const getDevelopmentNode = (graphId: GraphId, id: NodeId): DevelopmentNode | undefined =>
  developmentGraphById.get(graphId)?.nodes.find((node) => node.id === id);
