export type Category =
  | "Warm-up"
  | "Pre-Handstand"
  | "Abs"
  | "Core"
  | "Handstand";

export type Exercise = {
  id: string;
  name: string;
  category: Category;
  image: string;
  target: string;
  cues: [string, string];
  easier: string;
  swaps: string[];
};

export type WorkoutDay = {
  day: number;
  title: string;
  focus: string;
  intensity: "Moderate" | "Focused" | "Light" | "Strong";
  pre: string[];
  core: string[];
  skill: string;
  cooldown: [string, string];
};

const gif = (name: string) => `${import.meta.env.BASE_URL}exercises/${name}.gif`;

export const exercises: Record<string, Exercise> = {
  "wrist-palms": {
    id: "wrist-palms",
    name: "Quadruped Palm Lifts",
    category: "Warm-up",
    image: gif("warmup_palm_lifts"),
    target: "8–12 controlled lifts",
    cues: ["Keep every fingertip heavy", "Lift the palm without rocking back"],
    easier: "Work one hand at a time.",
    swaps: ["scap-pushup", "shoulder-sweep"],
  },
  "shoulder-sweep": {
    id: "shoulder-sweep",
    name: "Kneeling Shoulder Sweep",
    category: "Warm-up",
    image: gif("warmup_shoulder_sweep"),
    target: "6–10 slow sweeps",
    cues: ["Ribs stay down", "Reach tall without leaning back"],
    easier: "Use a smaller overhead range.",
    swaps: ["wrist-palms", "scap-pushup"],
  },
  "scap-pushup": {
    id: "scap-pushup",
    name: "Straight-Arm Scap Push-up",
    category: "Warm-up",
    image: gif("warmup_scap_pushup"),
    target: "8–12 smooth reps",
    cues: ["Lock the elbows", "Push the floor away at the top"],
    easier: "Perform from the knees.",
    swaps: ["wrist-palms", "shoulder-sweep"],
  },
  "pike-shift": {
    id: "pike-shift",
    name: "Pike Weight Shift",
    category: "Pre-Handstand",
    image: gif("d1_pike_weight_shift_v3"),
    target: "6–10 slow reps",
    cues: ["Feet stay grounded", "Elbows locked; shoulders move forward"],
    easier: "Reduce the forward shift.",
    swaps: ["kneeling-lean", "pike-elevation"],
  },
  "support-hold": {
    id: "support-hold",
    name: "Parallette Support Hold",
    category: "Pre-Handstand",
    image: gif("d1_support_hold"),
    target: "15–30 second hold",
    cues: ["Press tall through straight arms", "Keep shoulders away from ears"],
    easier: "Keep more weight through the feet.",
    swaps: ["support-shrugs", "box-pike"],
  },
  "hollow-tuck": {
    id: "hollow-tuck",
    name: "Hollow Tuck Hold",
    category: "Abs",
    image: gif("d1_hollow_tuck_hold"),
    target: "20–30 second hold",
    cues: ["Flatten the lower back", "Exhale and keep ribs tucked"],
    easier: "Bring knees closer to the chest.",
    swaps: ["boat-hold", "hollow-one-leg"],
  },
  "dead-bug": {
    id: "dead-bug",
    name: "Controlled Dead Bug",
    category: "Core",
    image: gif("d1_dead_bug"),
    target: "6–10 total reps",
    cues: ["Move opposite arm and leg", "Stop before the back arches"],
    easier: "Move only the legs.",
    swaps: ["cross-press", "hollow-reach"],
  },
  "plank-tap": {
    id: "plank-tap",
    name: "Parallette Plank Shoulder Tap",
    category: "Core",
    image: gif("d1_plank_shoulder_tap"),
    target: "6–12 total taps",
    cues: ["Keep hips square", "Shift slowly before lifting a hand"],
    easier: "Widen the feet or work from knees.",
    swaps: ["kneeling-plank-tap", "plank-tap-out"],
  },
  "bent-compression": {
    id: "bent-compression",
    name: "Bent-Knee Compression Lift",
    category: "Abs",
    image: gif("d1_bent_knee_compression"),
    target: "6–10 controlled lifts",
    cues: ["Press down through the bars", "Lift knees without swinging"],
    easier: "Lift one foot at a time.",
    swaps: ["single-leg-compression", "straight-compression"],
  },
  "wall-l": {
    id: "wall-l",
    name: "Wall Inverted-L Hold",
    category: "Handstand",
    image: gif("d1_wall_inverted_l_v2"),
    target: "15–25 second hold",
    cues: ["Stack shoulders over the bars", "Push tall and keep hips high"],
    easier: "Walk the feet lower on the wall.",
    swaps: ["box-toe-light", "wall-alignment"],
  },
  "support-shrugs": {
    id: "support-shrugs",
    name: "Support Shrugs",
    category: "Pre-Handstand",
    image: gif("d2_support_shrugs"),
    target: "8–12 reps",
    cues: ["Elbows remain locked", "Press tall, then lower a few centimetres"],
    easier: "Keep the feet more heavily grounded.",
    swaps: ["support-hold", "kneeling-lean"],
  },
  "box-pike": {
    id: "box-pike",
    name: "Box-Pike Alignment Hold",
    category: "Pre-Handstand",
    image: gif("d2_box_pike_hold"),
    target: "20–30 second hold",
    cues: ["Hips over shoulders", "Lock elbows and look between hands"],
    easier: "Use a lower box or wall-supported pike.",
    swaps: ["wall-l", "pike-shift"],
  },
  "tuck-support": {
    id: "tuck-support",
    name: "Tuck Support Hold",
    category: "Abs",
    image: gif("d2_tuck_support_v2"),
    target: "8–20 second hold",
    cues: ["Press tall before lifting", "Pull knees toward the chest"],
    easier: "Let the toes skim the floor.",
    swaps: ["supported-knee-raise", "bent-compression"],
  },
  "straight-compression": {
    id: "straight-compression",
    name: "Straight-Leg Compression Lift",
    category: "Abs",
    image: gif("d2_straight_leg_compression"),
    target: "6–10 lifts",
    cues: ["Keep knees straight", "Lean forward from the hips"],
    easier: "Bend one knee.",
    swaps: ["single-leg-compression", "bent-compression"],
  },
  "mountain-climber": {
    id: "mountain-climber",
    name: "Slow Mountain Climber",
    category: "Core",
    image: gif("d2_mountain_climber"),
    target: "8–12 total reps",
    cues: ["Move without bouncing", "Keep shoulders over the bars"],
    easier: "Elevate the parallettes on a stable platform.",
    swaps: ["plank-knee-elbow", "cross-press"],
  },
  "side-plank": {
    id: "side-plank",
    name: "Side-Plank Stability Hold",
    category: "Core",
    image: gif("d2_side_plank"),
    target: "15–25 sec per side",
    cues: ["Stack shoulders and hips", "Feet stay on the floor—not the bars"],
    easier: "Place the lower knee down.",
    swaps: ["kneeling-plank-tap", "plank-tap-out"],
  },
  "box-toe-light": {
    id: "box-toe-light",
    name: "Box-Pike Toe Lightener",
    category: "Handstand",
    image: gif("d2_box_toe_lightener_v2"),
    target: "4–8 controlled floats",
    cues: ["Hands stay firmly on both bars", "Float one or both toes without jumping"],
    easier: "Lighten one foot only.",
    swaps: ["wall-l", "wall-alignment"],
  },
  "kneeling-lean": {
    id: "kneeling-lean",
    name: "Kneeling Shoulder Lean",
    category: "Pre-Handstand",
    image: gif("d3_kneeling_shoulder_lean"),
    target: "6–10 slow reps",
    cues: ["Keep ribs tucked", "Load the shoulders with straight arms"],
    easier: "Move the knees closer to the bars.",
    swaps: ["pike-shift", "support-shrugs"],
  },
  "partial-wall-walk": {
    id: "partial-wall-walk",
    name: "Partial Wall Walk",
    category: "Pre-Handstand",
    image: gif("d3_partial_wall_walk"),
    target: "3–5 careful climbs",
    cues: ["Move one foot at a time", "Stop before the shoulders fatigue"],
    easier: "Walk only to a steep plank.",
    swaps: ["box-pike", "wall-l"],
  },
  "hollow-rocks": {
    id: "hollow-rocks",
    name: "Small Hollow Rocks",
    category: "Abs",
    image: gif("d3_hollow_rocks_v2"),
    target: "8–15 rocks",
    cues: ["Keep the hollow shape fixed", "Rock from shoulders to hips"],
    easier: "Hold still in a tuck.",
    swaps: ["hollow-tuck", "boat-hold"],
  },
  "plank-saw": {
    id: "plank-saw",
    name: "Controlled Plank Saw",
    category: "Core",
    image: gif("d3_plank_saw"),
    target: "6–10 slow reps",
    cues: ["Move as one solid line", "Do not let the low back sag"],
    easier: "Use a smaller range.",
    swaps: ["mountain-climber", "plank-knee-elbow"],
  },
  "cross-press": {
    id: "cross-press",
    name: "Dead-Bug Cross Press",
    category: "Core",
    image: gif("d3_deadbug_cross_press_v2"),
    target: "5–8 reps per side",
    cues: ["Press hand into opposite knee", "Keep pelvis still as the other leg extends"],
    easier: "Tap the heel close to the hips.",
    swaps: ["dead-bug", "plank-tap-out"],
  },
  "kneeling-plank-tap": {
    id: "kneeling-plank-tap",
    name: "Kneeling Plank Tap",
    category: "Core",
    image: gif("d3_kneeling_plank_tap"),
    target: "8–12 total taps",
    cues: ["Stay tall through the support arm", "Keep hips quiet"],
    easier: "Widen the knees.",
    swaps: ["plank-tap", "side-plank"],
  },
  "wall-alignment": {
    id: "wall-alignment",
    name: "Chest-to-Wall Line Hold",
    category: "Handstand",
    image: gif("d3_chest_wall_alignment"),
    target: "15–25 second hold",
    cues: ["Ribs in; glutes lightly squeezed", "Push tall with toes on the wall"],
    easier: "Move hands slightly farther from the wall.",
    swaps: ["wall-l", "wall-elevation"],
  },
  "frog-prep": {
    id: "frog-prep",
    name: "Assisted Frog-Stand Prep",
    category: "Pre-Handstand",
    image: gif("d4_assisted_frog_prep"),
    target: "5–8 controlled weight shifts",
    cues: ["Look slightly forward", "Keep one or both toes available for support"],
    easier: "Keep both feet fully grounded.",
    swaps: ["pike-shift", "box-toe-light"],
  },
  "pike-elevation": {
    id: "pike-elevation",
    name: "Pike Shoulder Elevation",
    category: "Pre-Handstand",
    image: gif("d4_pike_elevation"),
    target: "8–12 reps",
    cues: ["Keep arms straight", "Press shoulders toward the ears"],
    easier: "Bring feet closer and reduce the load.",
    swaps: ["support-shrugs", "kneeling-lean"],
  },
  "supported-knee-raise": {
    id: "supported-knee-raise",
    name: "Supported Knee Raise",
    category: "Abs",
    image: gif("d4_supported_knee_raise"),
    target: "6–10 reps",
    cues: ["Start with tall shoulders", "Curl the pelvis as knees rise"],
    easier: "Raise one knee at a time.",
    swaps: ["tuck-support", "bent-compression"],
  },
  "plank-knee-elbow": {
    id: "plank-knee-elbow",
    name: "Plank Knee-to-Elbow",
    category: "Core",
    image: gif("d4_plank_knee_elbow"),
    target: "6–10 total reps",
    cues: ["Round slightly as the knee comes in", "Return to a strong plank"],
    easier: "Drive the knee only halfway forward.",
    swaps: ["mountain-climber", "plank-saw"],
  },
  "boat-hold": {
    id: "boat-hold",
    name: "Boat Hold",
    category: "Abs",
    image: gif("d4_boat_hold"),
    target: "20–30 second hold",
    cues: ["Lift through the chest", "Keep the waist braced, not collapsed"],
    easier: "Hold behind the thighs.",
    swaps: ["hollow-tuck", "hollow-one-leg"],
  },
  "hollow-reach": {
    id: "hollow-reach",
    name: "Hollow Overhead Reach",
    category: "Core",
    image: gif("d4_hollow_overhead_reach"),
    target: "6–10 reaches",
    cues: ["Low back stays heavy", "Reach only as far as ribs stay down"],
    easier: "Keep arms aimed toward the ceiling.",
    swaps: ["dead-bug", "cross-press"],
  },
  "wall-elevation": {
    id: "wall-elevation",
    name: "Handstand Shoulder Elevation",
    category: "Handstand",
    image: gif("d4_wall_shoulder_elevation"),
    target: "6–10 controlled reps",
    cues: ["Stay chest-to-wall", "Move only through the shoulder blades"],
    easier: "Perform in a box-pike position.",
    swaps: ["wall-alignment", "chest-wall"],
  },
  "wall-kickup": {
    id: "wall-kickup",
    name: "Controlled Wall Kick-up",
    category: "Pre-Handstand",
    image: gif("d5_controlled_wall_kickup_v2"),
    target: "3–5 calm entries",
    cues: ["Kick softly to the wall", "Grip both bars before the legs leave"],
    easier: "Use a smaller kick and stop short of vertical.",
    swaps: ["partial-wall-walk", "wall-l"],
  },
  "chest-wall": {
    id: "chest-wall",
    name: "Chest-to-Wall Handstand",
    category: "Pre-Handstand",
    image: gif("d5_chest_wall_hold"),
    target: "15–25 second hold",
    cues: ["Push tall and point toes", "Keep a small, controlled wall contact"],
    easier: "Move the hands farther from the wall.",
    swaps: ["wall-alignment", "box-pike"],
  },
  "tuck-support-2": {
    id: "tuck-support-2",
    name: "Tuck Support",
    category: "Abs",
    image: gif("d5_tuck_support"),
    target: "10–20 second hold",
    cues: ["Press tall through both bars", "Lift knees without leaning back"],
    easier: "Keep one toe touching down.",
    swaps: ["tuck-support", "supported-knee-raise"],
  },
  "hollow-one-leg": {
    id: "hollow-one-leg",
    name: "One-Leg Hollow Extension",
    category: "Abs",
    image: gif("d5_hollow_one_leg"),
    target: "6–10 total changes",
    cues: ["Keep the back flat", "Switch legs without losing the tuck"],
    easier: "Keep both knees bent.",
    swaps: ["hollow-tuck", "boat-hold"],
  },
  "single-leg-compression": {
    id: "single-leg-compression",
    name: "Single-Leg Compression Lift",
    category: "Abs",
    image: gif("d5_single_leg_compression"),
    target: "5–8 reps per side",
    cues: ["Lock the lifting knee", "Press down before the foot rises"],
    easier: "Bend the non-working knee.",
    swaps: ["bent-compression", "straight-compression"],
  },
  "plank-tap-out": {
    id: "plank-tap-out",
    name: "Plank Tap-Out",
    category: "Core",
    image: gif("d5_plank_tap_out"),
    target: "6–10 total taps",
    cues: ["Keep shoulders level", "Touch wide without rotating the hips"],
    easier: "Use a wider foot position.",
    swaps: ["plank-tap", "kneeling-plank-tap"],
  },
  "heel-pullaway": {
    id: "heel-pullaway",
    name: "Wall Heel Pull-Away",
    category: "Handstand",
    image: gif("d5_heel_pullaway_v2"),
    target: "3–6 controlled floats",
    cues: ["Pull heels only a few centimetres", "Return to the wall before shape breaks"],
    easier: "Float one heel at a time.",
    swaps: ["wall-elevation", "wall-kickup"],
  },
};

export const universalWarmup = ["wrist-palms", "shoulder-sweep", "scap-pushup"];

export const workouts: WorkoutDay[] = [
  {
    day: 1,
    title: "Foundation & Abs",
    focus: "Build straight-arm confidence, hollow control and calm wall loading.",
    intensity: "Moderate",
    pre: ["pike-shift", "support-hold"],
    core: ["hollow-tuck", "dead-bug", "plank-tap", "bent-compression"],
    skill: "wall-l",
    cooldown: ["Wrist flexor stretch", "Child’s-pose shoulder reach"],
  },
  {
    day: 2,
    title: "Compression & Tuck Strength",
    focus: "Own the support position and build the compression needed for future L-sits.",
    intensity: "Strong",
    pre: ["support-shrugs", "box-pike"],
    core: ["tuck-support", "straight-compression", "mountain-climber", "side-plank"],
    skill: "box-toe-light",
    cooldown: ["Forearm extensor stretch", "Upper-back reach"],
  },
  {
    day: 3,
    title: "Light Line & Control",
    focus: "A lighter wrist-and-shoulder day for line awareness, anti-rotation and quality.",
    intensity: "Light",
    pre: ["kneeling-lean", "partial-wall-walk"],
    core: ["hollow-rocks", "plank-saw", "cross-press", "kneeling-plank-tap"],
    skill: "wall-alignment",
    cooldown: ["Prayer wrist stretch", "Thread-the-needle"],
  },
  {
    day: 4,
    title: "Abs & Overhead Strength",
    focus: "Link pelvic control, overhead push and controlled knee-raise strength.",
    intensity: "Strong",
    pre: ["frog-prep", "pike-elevation"],
    core: ["supported-knee-raise", "plank-knee-elbow", "boat-hold", "hollow-reach"],
    skill: "wall-elevation",
    cooldown: ["Palm-down wrist stretch", "Lat-and-shoulder reach"],
  },
  {
    day: 5,
    title: "Integration & Balance",
    focus: "Bring the week together with accurate entries, support and small balance corrections.",
    intensity: "Focused",
    pre: ["wall-kickup", "chest-wall"],
    core: ["tuck-support-2", "hollow-one-leg", "single-leg-compression", "plank-tap-out"],
    skill: "heel-pullaway",
    cooldown: ["Finger-back wrist reset", "Chest-and-shoulder opener"],
  },
];

export const categoryClass: Record<Category, string> = {
  "Warm-up": "tag-warm",
  "Pre-Handstand": "tag-pre",
  Abs: "tag-abs",
  Core: "tag-core",
  Handstand: "tag-handstand",
};
